In [1]:
import numpy as np

###### 1. The most basic kind of broadcast is with a scalar, in which you can perform a binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to perform that operation with the scalar for every element of the array. To try this out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.

In [2]:
vec = np.arange(1,11)
print("Original Vec : ",vec)
vec1 = vec+1
print("Adding 1 to Orginal Vector : ",vec1)

Original Vec :  [ 1  2  3  4  5  6  7  8  9 10]
Adding 1 to Orginal Vector :  [ 2  3  4  5  6  7  8  9 10 11]


In [3]:
print(len(vec),len(vec1))

10 10


###### 2. Now, create a 10 × 10 matrix A in which A[i][j] = i + j. You’ll be able to do this using the vector you just created, and adding it to a reshaped version of itself.

In [83]:
import numpy as np
ran = np.reshape((np.arange(1,101)),(-1,10))
print(ran)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


##### 3. A very common use of broadcasting is to standardize data, i.e., to make it have zero mean and unit variance. First, create a fake “data set” with 50 examples, each with five dimensions.

In [4]:
import numpy.random as npr
data = np.exp(npr.randn(50,5))

In [5]:
print(data)

[[ 2.61673607  0.76562657  0.83324237  0.44566036  0.93183355]
 [ 1.51045111  0.70812237  2.54990261  1.22909444  4.36062449]
 [ 0.17939426  3.68549659  0.51905896  2.12239819  0.31571261]
 [ 0.39028069  0.23304955  2.0555452   0.77094946  2.51669059]
 [ 1.17190665  0.50858337  0.20785353  0.08795482  2.00280362]
 [ 2.41476548  0.72642958  0.63823982  0.17910056  0.56759393]
 [ 1.71606315  2.31830262  4.7569714   0.29020389  0.95000865]
 [ 3.41749228  0.27781383  0.52576423  0.15530196  3.19590106]
 [ 0.36953656  2.39924371  0.19428479  2.75307964  1.96353106]
 [ 1.20486865  2.9338041   0.50959787  1.15088141  1.3341792 ]
 [ 2.00934628  1.57226983  0.1941097   3.08817599 11.19626769]
 [ 0.90339826  1.79558054  2.81975331  0.93763655  0.17193616]
 [ 0.70242134  1.60206847  4.45973101  0.74254281  1.04990633]
 [ 2.84837963  1.01681155  1.25079505  0.22365201  2.3819338 ]
 [ 2.24592686  0.41462412  0.59619891  0.97239293  0.35768621]
 [ 1.52559339  1.15921488  1.08530837  0.93267834  1.64

##### 4. Now, compute the mean and standard deviation of each column. This should result in two vectors of length 5. You’ll need to think a little bit about how to use the axis argument to mean and std. Store these vectors into variables and print both of them.

In [9]:
x = np.mean(data,axis=0)
print(x)
print("Length of the vector:",len(x))

[1.52062033 1.54985017 1.40833813 1.71615955 1.53303891]
Length of the vector: 5


In [10]:
y = np.std(data,axis=0)
print(y)
print("Length of the vector:",len(y))

[1.28276398 1.44995519 1.12954129 2.14423405 1.85240451]
Length of the vector: 5


### 5. Now standardize the data matrix by 1. subtracting the mean off of each column, and 2. dividing each column by its standard deviation. Do this via broadcasting, and store the result in a matrix called normalized. To verify that you successfully did it, compute the mean and standard deviation of the columns of normalized and print them out.

In [53]:
import numpy as np
import numpy.random as npr

In [55]:

Mean_of_data=np.mean(data,axis=0)
print("Mean of data =" ,Mean_of_data)

Mean of data = [156.5  136.     4.75]


In [57]:
normalized=np.divide((np.subtract(data,Mean_of_data)),np.std(data,axis=0)) 
print(normalized)

[[-0.3139653  -1.2031159  -0.57735027]
 [ 0.45575609  0.40693626  1.73205081]
 [ 1.28624496  1.41543047 -0.57735027]
 [-1.42803574 -0.61925083 -0.57735027]]


In [61]:
n_mean=np.mean(normalized,axis=0)
n_std=np.std(normalized,axis=0) 
print(n_mean)
print(n_std)

[ 0.00000000e+00 -2.77555756e-17  0.00000000e+00]
[1. 1. 1.]


**Performing the Hypothesis testing using the Chi-squared test**

In [11]:
from scipy.stats import chi2_contingency
  
# defining the table
data = [[141,68,4], [179,159,7],[220,216,4],[86,101,4]]
stat, p, dof, expected = chi2_contingency(data)
  
# interpret p-value
alpha = 0.05
print("p value is " + str(p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (H0 holds true)')

p value is 0.00044690833914947634
Dependent (reject H0)


**Since p_value < alpha we accept H0, ie, the age group and their movie genre inclination have a significant relation.**